model_name_or_path: Linaqruf/animagine-xl-3.0
lora:
  lora_r: 8
  lora_alpha: 32
data:
  parquet_file: /home/wukong-team/datasets/captions.parquet
  batch_size: 8
  drop_last: false
optimization:
  lr: 5.0E-5
  betas:
    - 0.9
    - 0.99
  weight_decay: 0.05
epochs: 10